import type { PricingModel } from '@/types/database'

export type ActivityBasketItem = {
  kind: 'activity'
  key: string
  studentId: string
  studentName: string
  className: string
  activityId: string
  activityName: string
  amountCents: number
}

export type ProgrammeBasketItem = {
  kind: 'programme'
  key: string
  studentId: string
  studentName: string
  className: string
  programmeId: string
  programmeName: string
  pricingModel: PricingModel
  amountCents: number
}

export type ParentBasketItem = ActivityBasketItem | ProgrammeBasketItem

// Payload shapes used by addItem (key is generated by BasketContext)
export type AddActivityPayload = Omit<ActivityBasketItem, 'key'>
export type AddProgrammePayload = Omit<ProgrammeBasketItem, 'key'>
export type AddItemPayload = AddActivityPayload | AddProgrammePayload

export type GuestBasketActivity = {
  activityId: string
  activityName: string // display only
  amountCents: number // display only; server re-fetches authoritative price
}

export type GuestBasketProgramme = {
  programmeId: string
  programmeName: string // display only
  pricingModel: PricingModel
  amountCents: number // display only; server re-fetches authoritative price
}

export type GuestCodeIdentification = {
  mode: 'code'
  pupilCode: string
  lookupFirstName: string // display only
  lookupClassName: string // display only
}

export type GuestManualIdentification = {
  mode: 'manual'
  childFirstName: string
  childLastName: string
  childClassId: string
  childClassName: string // display only
}

export type GuestIdentification = GuestCodeIdentification | GuestManualIdentification

export type GuestBasket = GuestIdentification & {
  activities: GuestBasketActivity[]
  programmes: GuestBasketProgramme[]
  paymentLinkId?: string
}
